
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: CYGWIN - 3.5.4-1.x86_64 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        /cygdrive/c/Users/Bland/CLionProjects/CGame/cmake-build-debug/CMakeFiles/3.29.6/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/cygdrive/c/Users/Bland/AppData/Local/JetBrains/CLion2024.2/cygwin_cmake/share/cmake-3.29.6/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        /cygdrive/c/Users/Bland/CLionProjects/CGame/cmake-build-debug/CMakeFiles/3.29.6/CompilerIdCXX/a.exe
      
